-- Crear los esquemas para cada microservicio
CREATE SCHEMA IF NOT EXISTS :POSTGRES_SCHEMA_WAREHOUSE;
CREATE SCHEMA IF NOT EXISTS :POSTGRES_SCHEMA_MARKET;

-- Crear usuarios con los valores de las variables de entorno
CREATE USER :POSTGRES_USER_WAREHOUSE WITH PASSWORD :POSTGRES_PASSWORD_WAREHOUSE;
CREATE USER :POSTGRES_USER_MARKET WITH PASSWORD :POSTGRES_PASSWORD_MARKET;

-- Otorgar permisos a los usuarios para sus respectivos esquemas
GRANT USAGE ON SCHEMA :POSTGRES_SCHEMA_WAREHOUSE TO :POSTGRES_USER_WAREHOUSE;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, TRUNCATE ON ALL TABLES IN SCHEMA :POSTGRES_SCHEMA_WAREHOUSE TO :POSTGRES_USER_WAREHOUSE;

GRANT USAGE ON SCHEMA :POSTGRES_SCHEMA_MARKET TO :POSTGRES_USER_MARKET;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, TRUNCATE ON ALL TABLES IN SCHEMA :POSTGRES_SCHEMA_MARKET TO :POSTGRES_USER_MARKET;

-- Otorgar permisos generales para conexión a la base de datos
GRANT CONNECT ON DATABASE restaurant_db TO :POSTGRES_USER_WAREHOUSE;
GRANT CONNECT ON DATABASE restaurant_db TO :POSTGRES_USER_MARKET;
